apiVersion: v1
kind: Secret
metadata:
    name: mysql-pass
type: Opaque
data:
    mysql-root-password: TWFsYXlhMTQzIQ==       ## rootpassword
    mysql-user-password: TWFsYXlhMTQzIQ==       ## userpassword
