server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-server:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-auth:8080/auth/realms/micro-service

management:
  tracing:
    sampling:
      probability: 1.0